name: low_light
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=12.1
  - pillow>=9.0.0
  - numpy
  - matplotlib
  - scipy
  - pip
  - pip:
    - lpips>=0.1.4
